### PR TITLE
Allow to get exit status while process is running

### PR DESCRIPTION
**Pull request by whimboo**
@jgraham or @andreastt can one of you please have a look?

---
This change is [Reviewable](https://reviewable.io/reviews/jgraham/rust_mozrunner/14)

### CODE REVIEW

**Comment by jgraham** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/runner.rs, line 122 at r1](https://reviewable.io:443/reviews/jgraham/rust_mozrunner/14#-KtkIoTvfqKT_Af48gHI:-KtkIoTvfqKT_Af48gHJ:b-vexnzp) ([raw file](https://github.com/jgraham/rust_mozrunner/blob/a543fbc781612866a097a6dd2f7ce90270eadaf1/src/runner.rs#L122)):*
> ```Rust
>     fn status(&mut self) -> IoResult<Option<process::ExitStatus>> {
>         if let Some(ref mut p) = self.process {
>             return p.try_wait();
> ```

```
pr.as_mut().map(|p| p.try_wait()).unwrap_or(Ok(None))
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jgraham/rust_mozrunner/14)*

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jgraham/rust_mozrunner/14)*

**Comment by whimboo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/runner.rs, line 122 at r1](https://reviewable.io:443/reviews/jgraham/rust_mozrunner/14#-KtkIoTvfqKT_Af48gHI:-KtksKlhsG2wgfgZrFph:bqzppf0) ([raw file](https://github.com/jgraham/rust_mozrunner/blob/a543fbc781612866a097a6dd2f7ce90270eadaf1/src/runner.rs#L122)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

```
pr.as_mut().map(|p| p.try_wait()).unwrap_or(Ok(None))
```

</blockquote></details>

Ok, I fixed that with my last update. A bit cryptic still for me but I think I got most of it now. Thanks for the advice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jgraham/rust_mozrunner/14)*

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jgraham/rust_mozrunner/14)*

**Pull request merged**
